apiVersion: apps/v1
kind: Deployment
metadata:
  name: raclavsky-deployment
  labels:
    app: raclavsky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raclavsky
  template:
    metadata:
      labels:
        app: raclavsky
    spec:
      imagePullSecrets:
        - name: google-artifacts-secret
      containers:
        - name: raclavsky
          image: europe-west3-docker.pkg.dev/stodola-planovac/raclavskycz/raclavskycz:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 10Mi
              cpu: 20m
            limits:
              memory: 15Mi
