apiVersion: apps/v1
kind: Deployment
metadata:
  name: raclavsky-deployment
  labels:
    app: raclavsky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raclavsky
  template:
    metadata:
      labels:
        app: raclavsky
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: raclavsky
          image: voxfpd/raclavsky-cz:1.0.0
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 10Mi
              cpu: 2m
            limits:
              memory: 15Mi
              cpu: 3m
