apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: raclavskycz
resources:
- namespace.yml
- deployment.yml
- service.yml
images:
- name: europe-west3-docker.pkg.dev/stodola-planovac/raclavskycz/raclavskycz
  newName: europe-west3-docker.pkg.dev/stodola-planovac/raclavskycz/raclavskycz
  newTag: 2e6c00a
