apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: raclavskycz
resources:
- deployment.yml
- service.yml
images:
- name: voxfpd/raclavsky-cz
  newName: voxfpd/raclavsky-cz
  newTag: 2a022fb
- name: voxfpd/stodolawebtemp
  newName: voxfpd/stodolawebtemp
  newTag: 14bb197
