apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: raclavskycz
resources:
- namespace.yml
- deployment.yml
- service.yml
- dockerhub-secret.yml
images:
- name: voxfpd/raclavsky-cz
  newName: voxfpd/raclavsky-cz
  newTag: 65bfda4
