apiVersion: v1
kind: Service
metadata:
  name: raclavsky-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: raclavsky

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: raclavsky-k3s-ingress-rule
spec:
  entryPoints:
    - websecure
  tls:
    secretName: raclavsky-root-cert-secret
  routes:
    - match: Host(`raclavsky.k3s.raclavsky.cz`, `www.raclavsky.k3s.raclavsky.cz`)
      kind: Rule
      services:
        - name: raclavsky-service
          port: 80
          scheme: http

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: raclavsky-ingress-rule
spec:
  entryPoints:
    - websecure
  tls:
    secretName: raclavsky-root-cert-secre
  routes:
    - match: Host(`raclavsky.cz`, `www.raclavsky.cz`)
      kind: Rule
      services:
        - name: raclavsky-service
          port: 80
          scheme: http

---

apiVersion: v1
kind: Secret
metadata:
  name: raclavsky-root-cert-secret
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "cert-manager/raclavsky-root-cert-secret"