apiVersion: v1
kind: Namespace
metadata:
  name: raclavskycz
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: cert-manager/raclavsky-root-cert-secret
  name: raclavsky-root-cert-secret
  namespace: raclavskycz
---
apiVersion: v1
kind: Service
metadata:
  name: raclavsky-service
  namespace: raclavskycz
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: raclavsky
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: raclavsky
  name: raclavsky-deployment
  namespace: raclavskycz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raclavsky
  template:
    metadata:
      labels:
        app: raclavsky
    spec:
      containers:
      - image: europe-west3-docker.pkg.dev/stodola-planovac/raclavskycz/raclavskycz:2e6c00a
        name: raclavsky
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 15Mi
          requests:
            cpu: 20m
            memory: 10Mi
      imagePullSecrets:
      - name: google-artifacts-secret
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: raclavsky-ingress-rule
  namespace: raclavskycz
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`raclavsky.cz`) || Host(`www.raclavsky.cz`)
    services:
    - name: raclavsky-service
      port: 80
      scheme: http
  tls:
    secretName: raclavsky-root-cert-secret
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: raclavsky-k3s-ingress-rule
  namespace: raclavskycz
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`raclavsky.k3s.raclavsky.cz`) || Host(`www.raclavsky.k3s.raclavsky.cz`)
    services:
    - name: raclavsky-service
      port: 80
      scheme: http
  tls:
    secretName: raclavsky-root-cert-secret
