name: Build & push & deploy

on:
  push:
    branches:
      - master

jobs:
  buildPushDeploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/969800801614/locations/global/workloadIdentityPools/github-id-pool/providers/github-id-provider'
          service_account: 'github-actions@stodola-planovac.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - id: 'secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@v2'
        with:
          secrets: |-
            kubeConfig:stodola-planovac/global-cluster-kubeconfig

      - name: Authorize Docker push
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev

      - name: Build docker image
        run: make build

      - name: Push docker image
        run: make push

      - uses: ThomasKliszowski/setup-kubectl@v1
        with:
          kube-config: ${{ steps.secrets.outputs.token }}
          kube-version: 1.24.3

      - name: Make kube configs
        run: make build-kustomize

      - name: Roll new deployment
        run: make apply